# build environment
FROM node:16.13.1 as react-build
WORKDIR /app
COPY . ./

ARG REACT_APP_ENV
ENV REACT_APP_ENV $REACT_APP_ENV

ARG REACT_APP_FIREBASE_AUTHDOMAIN
ENV REACT_APP_FIREBASE_AUTHDOMAIN $REACT_APP_FIREBASE_AUTHDOMAIN

ARG REACT_APP_FIREBASE_PROJECTID
ENV REACT_APP_FIREBASE_PROJECTID $REACT_APP_FIREBASE_PROJECTID

ARG REACT_APP_FIREBASE_STORAGEBUCKET
ENV REACT_APP_FIREBASE_STORAGEBUCKET $REACT_APP_FIREBASE_STORAGEBUCKET

ARG REACT_APP_FIREBASE_MESSAGINGSENDERID
ENV REACT_APP_FIREBASE_MESSAGINGSENDERID $REACT_APP_FIREBASE_MESSAGINGSENDERID

ARG REACT_APP_FIREBASE_APPID
ENV REACT_APP_FIREBASE_APPID $REACT_APP_FIREBASE_APPID

ARG REACT_APP_FIREBASE_MEASURMENTID
ENV REACT_APP_FIREBASE_MEASURMENTID $REACT_APP_FIREBASE_MEASURMENTID

ARG REACT_APP_FIREBASE_APIKEY
ENV REACT_APP_FIREBASE_APIKEY $REACT_APP_FIREBASE_APIKEY

ARG UNPROTECTED_TOKEN
ENV UNPROTECTED_TOKEN $UNPROTECTED_TOKEN

RUN npm install
RUN npm run build

# server environment
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/configfile.template

COPY --from=react-build /app/build /usr/share/nginx/html

ENV PORT 8080
ENV HOST 0.0.0.0
EXPOSE 8080
CMD sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"